# BERTForSequenceClassification model config
_target_: models.bert_module.BERTForSequenceClassificationModule

config:
  pretrained_model_name_or_path: "bert-base-uncased" 
  num_labels: 2 # specific to dataset, eg. 2 for {"sst2", "mrpc", "qnli"}, 3 for {"mnli"}

# adamw and scheduler args
lr: 1e-5
eps: 1e-6
warmup: null # 0.1 or empty for None
scheduler_training_steps: null