# RoBERTaForSequenceClassification model config
_target_: models.bert_module.RoBERTaForSequenceClassificationModule

config:
  pretrained_model_name_or_path: "roberta-base" 
  num_labels: 38 # specific to dataset {"conll2003": 10, "wnut_17": 14, "conll2012_ontonotesv5" : 38}

# adamw and scheduler args
lr: 1e-5
eps: 1e-6
warmup: null # 0.1 or empty for None
scheduler_training_steps: null