_target_: src.datamodules.simulation_datamodule.SimulationDatamodule
batch_size: 32
pin_memory: False

# max_train_batches: 1000
# max_val_batches: 100
# max_test_batches: 100

transforms:
  _target_: src.datamodules.components.transforms.core.Compose
  transforms:
    - _target_: src.datamodules.components.transforms.core.ComplexToReal
    - _target_: src.datamodules.components.transforms.target_transforms.NormalizeAngles
      normalize: true
      elevation_only: true
    - _target_: src.datamodules.components.transforms.target_transforms.NormalizeDelays
      t_sym: 1

dataset:
  _target_: src.datamodules.components.datasets.simulation_dataset.SimulationDataset
  num_ant_tx: 4
  num_ant_rx: 16
  num_carriers: 64
  num_symbols: 14
  scs: 150000.0
  snr: 0.0
  path_loss: 0.0
  num_paths: 5
  center_dod: 0.0
  center_doa: 0.0
  dod_spread: 2.0
  doa_spread: 5.0
