_target_: datamodules.ner_datamodule.WNUT17DataModule
ner_dataset: wnut_17 # from : {"conll2003", "wnut_17", "conll2012_ontonotesv5"} 
batch_size: 64
num_workers: 1
model_type: ${model.config.pretrained_model_name_or_path}
num_splits: ${sfl.num_clients}
truncate: 100