sfl:
  num_clients: 8
  num_rounds: 10
  num_epochs: 50
  process: "parallel" # from : {"parallel" or "sequential"}
  ckpt_path: "results/model_ckpts/"
  master_path: "results/master/"

training:
  run_name: "run_0/"
  ckpt_path: "client_ckpts/"
  master_path: "master_ckpts/"
  log_path: "logs/"

model:
  config:
    pretrained_model_name_or_path: "roberta-base" # from : {"bert-base-uncased", "roberta-base"}  
    num_labels: 2 # specific to dataset, eg. 2 for {"sst2", "mrpc", "qnli"}, 3 for {"mnli"}

optimizer:
  lr: 1e-5
  eps: 1e-8

data:
  glue_dataset: "sst2" # from : {"sst2", "mrpc", "qnli", "mnli"} 
  batch_size: 256
  num_workers: 1
  model_type: ${model.config.pretrained_model_name_or_path}
  num_splits: ${sfl.num_clients}
  # truncate: 250

trainer:
  # default_root_dir: "lightning_logs/"

  # min_epochs: 1 # prevents early stopping
  max_epochs: ${sfl.num_epochs}

  accelerator: cuda
  # devices: 1

  # mixed precision for extra speed-up
  # precision: 16

  # comment out these lines if you are NOT using a simulation dataset
  # limit_train_batches: 100
  # limit_val_batches: 10
  # limit_test_batches: 10

  # perform a validation loop every N training epochs
  # check_val_every_n_epoch: 1

  # set True to to ensure deterministic results
  # makes training slower but gives more reproducibility than just setting seeds
  deterministic: False